name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
      - run: ls
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # Export all traces as trace viewers
      - name: Export traces to viewer format
        run: |
          mkdir -p trace-viewer
          find . -name trace.zip | while read trace; do
            npx playwright show-trace "$trace" --output=trace-viewer
          done

      # Deploy the trace viewer to a branch
      - name: Publish trace viewer to test-automation-report branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./trace-viewer
          publish_branch: test-automation-report
          force_orphan: true
          commit_message: "chore: publish Playwright trace viewer"
