name: Add allure-playwright dependency

on:
  workflow_dispatch:

jobs:
  add-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize empty test-automation-report branch
        if: github.ref == 'refs/heads/main'  # Only on main
        run: |
          git checkout --orphan test-automation-report
          git rm -rf .
          echo "# Initial commit" > README.md
          git add README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "init empty report branch"
          git push origin test-automation-report
